version: '3'
services:
  app:
    build: .
    ports:
      - "3000"
    expose:
      - "3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
